sudo: false

language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - brew cleanup

matrix:
  include:
    - os: osx
      language: shell
      python: 3.6  # default available
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      after_success:
        - codecov

addons:
  apt:
    packages:
      - libenchant-dev
    update: true
  homebrew:
    packages:
      - enchant
    update: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv ./venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./venv/bin/activate; fi
  - python --version
  - pip install -U pip
  - pip install -U pytest-cov

install:
  - pip install -r requirements.txt
  - python -m nltk.downloader words

script:
  - pytest --cov==gibberish
